# Jeckyl configuration
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: GFM
remote_theme: pages-themes/midnight@v0.2.0
is_project_page: false

title: "Christopher Durham's Porfolio"
description: "Engine & Tools Programming"
show_downloads: false
